## DATA SCIENCE ONLINE TRAINING - HARVARD edX

#################################################################################
## CHAPTER 5. PRODUCTIVITY TOOLS
#################################################################################

<<<<<<< HEAD
setwd("~/Documents/Trainings/DataScienceTraining")
=======
setwd("~/Documents/Trainings/R for Analytics")
>>>>>>> e9b2556e22f9d82e0337e10628a5eac57d688ace

###############################
## 

<<<<<<< HEAD

Key points
In terminal: configure git 
git config --global user.name "Your Name"
git config --global user.email "your@email.com"
In RStudio, create project > Version control > Git
Git pane: status symbols and color
Git actions:
  pull: pull changes from remote repo (if you are in collaboration with others)
add: stage files for commit; click on stage box under git pane
commit: commit to the local repo; click on "commit" button under git pane; add a commit message
push: push to the remote repo on Github
.gitignore file: details check https://git-scm.com/docs/gitignore


Code

ls #list dir content
mkdir folder_name #create directory called "folder_name"
rmdir folder_name  #remove an empty directory as long as it is empty
rm -r folder_name  #remove dir that is not empty, "r" stands for recursive
cd: change dir
../ # two dots represents parent dir
  . # single dot represents current workingdir 
cd ~/projects # concatenate with forward slashes
cd ../.. # change to two parent layer beyond
cd -  # whatever dir you were before
  cd  # return to the home dir

mv path-to-file path-to-destination-directory
rm filename-1 filename-2 filename-3
=======
>>>>>>> e9b2556e22f9d82e0337e10628a5eac57d688ace

Code
########### In terminal ###########
cd ~    # move to home directory
  mkdir projects    # make a new directory called projects
cd projects    # move to ~/projects directory
mkdir murders    # make new directory called murders inside of projects
cd murders    # move to ~/projects/murders/
mkdir data rda    # make two new directories, one is data the other is rda folder
ls    # to check if we indeed have one data folder and one rda folder
pwd    # check the current working directory
mkdir figs    # make a directory called figs to store figures
########## In RStudio ########
# pick existing directory as new project
getwd()    # to confirm current working directory
save()    # save into .rda file, .RData is also fine but less preferred
ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"

###############################
## R-Markdown

Code
# a sample code chunk
```{r}
summary(pressure)
```

# When echo=FALSE, code will be hided in output file
```{r echo=FALSE}
summary(pressure)
```

# use a descriptive name for each chunk for debugging purpose
```{r pressure-summary}
summary(pressure)
```

###############################
## Using Git at the command line

pwd
mkdir git-example
cd git-example
git clone https://github.com/rairizarry/murders.git
cd murders
ls
git status
echo "test" >> new-file.txt
echo "temporary" >> tmp.txt
git add new-file.txt
git status
git commit -m "adding a new file" 
git status
echo "adding a second line" >> new-file.txt
git commit -m "minor change to new-file" new-file.txt
git status
git add
git log new-file.txt
git push
git fetch
git merge
cd ~/projects/murders
git init
git add README.txt
git commit -m "First commit. Adding README.txt file just to get started"
git remote add origin "https://github.com/rairizarry/murders.git"
git push    # you may need to add these arguments the first time: --set-upstream origin master


Key points
Arguments typically are defined using a dash (-) or two dashes (--) followed by a letter of a word.
r: recursive. For example, rm -r <directory-name>: remove all files, subdirectories, files in subdirectories, subdirectories in subdirectories, etc.
Combine arguments: rm -rf directory-name
ls -a: Shows all files in the directories including hidden files (e.g. .git file when initializing using git init) (a for all).
ls -l: Returns more information about the files (i.e. l for long).
ls -t: Shows files in chronological order.
ls -r: Reverses the order of how files are shown.
ls -lart: Shows more information for all files in reverse chronological order.

###############################
## More Unix commands

Key Points
Getting Help: Use man + command name to get help (e.g. man ls). Note that it is not available for Git Bash. For Git Bash, you can use command -- help (e.g. ls --help).
Pipes: Pipes the results of a command to the command after the pipe. Similar to the pipe %>% in R. For example, man ls | less (and its equivalent in Git Bash: ls --help | less). Also useful when listing files with many files (e.g ls -lart | less).

Key points
* means any number of any combination of characters. Specifically, to list all html files: ls *.html and to remove all html files in a directory: rm *.html.
? means any single character. For example, to erase all files in the  form file-001.html with the numbers going from 1 to 999: rm file-???.html.
Combined wild cards: rm file-001.* to remove all files of the name file-001 regardless of suffix.
Warning: Combining rm with the * wild card can be dangerous. There are combinations of these commands that will erase your entire file system without asking you for confirmation. Make sure you understand how it works before using this wild card with the rm command.

Key points
Be aware of common commands and know what they do.
open/start - On the mac open filename tries to figure out the right application of the filename and open it with that application. This is a very useful command. On Git Bash, you can try start filename. Try opening an R or Rmd file with open or start: it should open with RStudio.

nano - A bare-bones text editor.

ln - create a symbolic link. We do not recommend its use, but you should be familiar with it.

tar - archive files and subdirectories of a directory into one file.

ssh - connect to another computer.

grep - search for patterns in a file.

awk/sed - These are two very powerful commands that permit you to find specific strings in files and change them.

Annotate



#*******************************
#*******************************
#*******************************
#*******************************
#*******************************


###############################
##
###############################
##
###############################
##
###############################
##
